### ISSUE TITLE
Table Component 

### ISSUE THREAD

**Issue by gjain-7** [Web-Team-IITI-Gymkhana/tpc-frontend#19]
A table component will have:
- filters (by _id_ also)
- column selection, pagination (from backend)
- on selecting a particular row open up a modal with all fields
- delete selection
- edit a row
- add a row. 
- Import multiple rows from csv
- export selection/all rows to csv
- Copy to clipboard - copy the ids of selected rows into clipboard and enable pasting somewhere else.

Implement this tabulated view for 
- Students
- Jobs
- Recruiters
- TPC Members
- Companies
- Offers
- Penalties
- Salary
- Faculty approval

**Comment by gjain-7** [comment]
Assigned to @Pradeep-Kumar-Rebbavarapu

**Comment by cse210001015** [comment]
Note:
1. The filters should also be present in the url.
2. Upon adding the filter the url should also change without reloading the website.
3. On a fresh load apply the filters from the url if any.

**Comment by Pradeep-Kumar-Rebbavarapu** [comment]
1) Table <Filter mapping , option mapping , column mapping , data , primary_column = id , visible_columns>
2) Import (Validation for null) , Export
3) Copy to clipboard (id's,column)
4) Filter from backend (comma seperated , on press enter gets the filter)
5) Delete Selection
6) Make action button (Delete , Import , Export)

**Comment by Pradeep-Kumar-Rebbavarapu** [comment]
1) Checking Filters and ordering
2) add Backend url in env
3) Split and clean the table component
